export {arrow} from './arrow';
export {vFloating} from './directives';
export type * from './types';
export {useFloating} from './useFloating';
export {useSearch} from './search';
export type {UseSearchReturn} from './search';
export {useFloatingPresenceStack} from './presence-stack';
export type {UseFloatingPresenceStackReturn} from './presence-stack';
export {useFloatingTopLayer} from './top-layer';
export type {UseFloatingTopLayerOptions} from './top-layer';
export {
  FloatingResults,
  /** @deprecated Use `FloatingResults`. */
  FloatingSearch,
} from './results-content';
export {useQuery} from './query';
export type {
  QueryInputLifecycleProps,
  UseQueryOptions,
  UseQueryReturn,
} from './query';
export {useCombobox} from './combobox';
export type {
  ComboboxInputLifecycleProps,
  UseComboboxOptions,
  UseComboboxReturn,
} from './combobox';
export {
  FloatingContent,
  FloatingClose,
  FloatingItem,
  FloatingReference,
  FloatingRoot,
  useFloatingRoot,
  useFloatingRootTopLayer,
} from './root';
export {
  autoPlacement,
  autoUpdate,
  computePosition,
  createAsyncSearchSource,
  createCombobox,
  createComboboxStatusFormatter,
  createQuery,
  createQueryStatusFormatter,
  createFloating,
  createFloatingContextScope,
  createFloatingTopLayer,
  createFuzzyMatcher,
  createFuzzySearch,
  createFuzzySearchSource,
  createSearch,
  createSearchRenderer,
  createFloatingPresenceStack,
  FLOATING_UI_PLUS_ARROW_ATTRIBUTE,
  FLOATING_UI_PLUS_ARROW_HEIGHT_ATTRIBUTE,
  createOverlayElement,
  createPortalBridge,
  createPortalNode,
  createPortalNodeController,
  detectOverflow,
  flip,
  focusManager,
  fuzzySearch,
  getArrowStyles,
  getContextArrowStyles,
  getDocumentTrapStack,
  getOverflowAncestors,
  hide,
  inline,
  limitShift,
  lockScroll,
  normalizeSearchText,
  offset,
  PLACEMENT,
  PLACEMENTS,
  platform,
  PortalBridge,
  PortalNodeController,
  SearchRenderer,
  FloatingPresenceStack,
  FloatingTopLayerController,
  provideFloatingContext,
  removePortalNode,
  resolvePortalRoot,
  requestFloatingContext,
  shift,
  size,
  supportsFloatingTopLayer,
  transformOrigin,
} from '@floating-ui-plus/web';
export type {
  ClickOptions,
  AsyncSearchSourceOptions,
  ControlledSearchState,
  ClientPointOptions,
  CompositeOptions,
  CompositeOrientation,
  Delay,
  DelayGroupOptions,
  DismissOptions,
  FloatingAttributes,
  FloatingContext,
  FloatingContextScope,
  FloatingController,
  FloatingData,
  FloatingElements,
  FloatingEvents,
  FloatingListItem as WebFloatingListItem,
  FloatingListItemOptions,
  FloatingOpenChangeEvent,
  FloatingOptions,
  FloatingOptionsSource,
  FloatingPlugin,
  FloatingPosition,
  FloatingRole,
  FloatingStyles,
  FloatingTopLayer,
  FocusManagerOptions,
  FocusOptions,
  FocusTarget,
  FuzzyMatchKind,
  FuzzySearch,
  FuzzySearchKey,
  FuzzySearchMatch,
  FuzzySearchOptions,
  FuzzySearchResult,
  FuzzySearchSource,
  HandleClose,
  HandleCloseContext,
  HoverOptions,
  ItemState,
  ListNavigationOptions,
  OpenChangeReason,
  OverlayOptions,
  PortalNodeOptions,
  PortalBridgeOptions,
  PortalBridgeStatus,
  PortalRoot,
  PortalRootResolver,
  PortalTarget,
  PortalTargetResolver,
  PortalTargetSource,
  PlacementConstant,
  RoleOptions,
  SearchHit,
  SearchHitMatch,
  SearchOptions,
  SearchPage,
  SearchRequest,
  SearchPhase,
  SearchRenderContext,
  SearchRendererOptions,
  SearchRenderers,
  SearchRenderOutput,
  SearchSnapshot,
  SearchSource,
  SearchSourceHandler,
  SearchSourceInput,
  SearchSourceItem,
  PresenceStackAddOptions,
  FloatingPresenceStackContext,
  FloatingPresenceStackOptions,
  PresenceStackListener,
  PresenceStackRecord,
  PresenceStackSnapshot,
  ComboboxOptions,
  ComboboxNavigationOptions,
  ComboboxQueryTriggerProps,
  ComboboxSnapshot,
  ComboboxStatusContext,
  ComboboxStatusFormatter,
  ComboboxStatusMessages,
  ComboboxStatusText,
  SafePolygonOptions,
  TransitionStatus,
  TransitionStyles,
  TransformOriginData,
  TransformOriginOptions,
  TypeaheadOptions,
  ValueOrGetter,
  WhileElementsMounted,
} from '@floating-ui-plus/web';
export {SearchController as WebSearchController} from '@floating-ui-plus/web';
export {
  click,
  clientPoint,
  dismiss,
  focus,
  hover,
  listNavigation,
  role,
  safePolygon,
  typeahead,
} from './interactions';
export {
  FloatingArrow,
  FloatingFocusManager,
  FloatingOverlay,
  FloatingPortal,
  useFloatingFocusManager,
} from './components';
export {
  Composite,
  CompositeItem,
  FloatingDelayGroup,
  FloatingList,
  FloatingListItem,
  FloatingNode,
  FloatingTree,
  NextFloatingDelayGroup,
  WebFloatingList,
  WebFloatingTree,
  useDelayGroup,
  useFloatingContextScope,
  useFloatingList,
  useFloatingTree,
} from './collections';
export {
  FloatingTransition,
  useFloatingTransition,
} from './transition';
